package com.seniorhub.models

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * Emergency Alert Model
 * Represents emergency situations and alerts
 */
@Parcelize
data class EmergencyAlert(
    val id: String = "",
    val userId: String = "",
    val type: EmergencyType = EmergencyType.MEDICAL_EMERGENCY,
    val severity: EmergencySeverity = EmergencySeverity.HIGH,
    val status: EmergencyStatus = EmergencyStatus.ACTIVE,
    val location: LocationData = LocationData(),
    val timestamp: Long = System.currentTimeMillis(),
    val description: String = "",
    val notes: String = "",
    val contactedServices: List<String> = emptyList(),
    val contactedFamily: List<String> = emptyList(),
    val responseTime: Long = 0, // Time taken to respond in milliseconds
    val resolvedAt: Long = 0,
    val resolvedBy: String = "",
    val resolutionNotes: String = "",
    val isAutoGenerated: Boolean = false,
    val triggeredBy: String = "", // "user", "system", "family", "health_monitor"
    val deviceInfo: String = "",
    val batteryLevel: Int = 0,
    val signalStrength: Int = 0,
    val followUpRequired: Boolean = false,
    val followUpDate: Long = 0,
    val attachments: List<String> = emptyList() // URLs to photos, audio, etc.
) : Parcelable

@Parcelize
data class LocationData(
    val latitude: Double = 0.0,
    val longitude: Double = 0.0,
    val address: String = "",
    val city: String = "",
    val province: String = "",
    val country: String = "",
    val accuracy: Float = 0f,
    val altitude: Double = 0.0,
    val speed: Float = 0f,
    val bearing: Float = 0f,
    val timestamp: Long = System.currentTimeMillis()
) : Parcelable

@Parcelize
enum class EmergencyType : Parcelable {
    MEDICAL_EMERGENCY,
    FALL_DETECTED,
    HEART_ATTACK,
    STROKE,
    DIABETIC_EMERGENCY,
    RESPIRATORY_DISTRESS,
    SEIZURE,
    UNCONSCIOUS,
    SEVERE_PAIN,
    ACCIDENT,
    FIRE,
    INTRUDER,
    NATURAL_DISASTER,
    TECHNICAL_ISSUE,
    LOST_OR_CONFUSED,
    MEDICATION_OVERDOSE,
    DEHYDRATION,
    HYPOTHERMIA,
    HYPERTHERMIA,
    OTHER
}

@Parcelize
enum class EmergencySeverity : Parcelable {
    LOW,
    MEDIUM,
    HIGH,
    CRITICAL,
    LIFE_THREATENING
}

@Parcelize
enum class EmergencyStatus : Parcelable {
    ACTIVE,
    ACKNOWLEDGED,
    IN_PROGRESS,
    RESOLVED,
    CANCELLED,
    FALSE_ALARM
}


